// Code generated by ent, DO NOT EDIT.

package ent

// CreateTodoInput represents a mutation input for creating todos.
type CreateTodoInput struct {
	Title     string
	Completed *bool
}

// Mutate applies the CreateTodoInput on the TodoMutation builder.
func (i *CreateTodoInput) Mutate(m *TodoMutation) {
	m.SetTitle(i.Title)
	if v := i.Completed; v != nil {
		m.SetCompleted(*v)
	}
}

// SetInput applies the change-set in the CreateTodoInput on the TodoCreate builder.
func (c *TodoCreate) SetInput(i CreateTodoInput) *TodoCreate {
	i.Mutate(c.Mutation())
	return c
}
